prgrms-web-devcourse-final-project/WEB1_1_Urdego_BE

- .github/workflows/google-java-format.yml
- .idea/modules.xml
- content_service/src/test/java/io/urdego/content_service/ContentServiceApplicationTests.java
- discovery_service/src/main/java/io/urdego/discovery_service/DiscoveryServiceApplication.java
- discovery_service/src/test/java/io/urdego/discovery_service/DiscoveryServiceApplicationTests.java
- game_service/src/main/java/io/urdego/game_service/GameServiceApplication.java
- game_service/src/test/java/io/urdego/game_service/GameServiceApplicationTests.java
- gateway_service/src/main/java/io/urdego/gateway_service/GatewayServiceApplication.java
- gateway_service/src/test/java/io/urdego/gateway_service/GatewayServiceApplicationTests.java
- user_service/src/main/java/io/urdego/user_service/UserServiceApplication.java
- user_service/src/main/java/io/urdego/user_service/auth/config/SecurityConfig.java
- user_service/src/main/java/io/urdego/user_service/auth/jwt/JwtFilter.java
- user_service/src/main/java/io/urdego/user_service/auth/jwt/JwtProvider.java
- user_service/src/test/java/io/urdego/user_service/UserServiceApplicationTests.java
> google java format 적용

- .github/workflows/google-java-format.yml
> Hotfix(#13) : google-java-format 재설정

- .github/workflows/google-java-format.yml
- discovery_service/src/main/java/io/urdego/discovery_service/DiscoveryServiceApplication.java
> Auto stash before rebase of "feature/discovery-server" onto "develop"

- .github/workflows/deploy.yml
- discovery_service/Dockerfile
- docker-compose.yml
- gateway_service/Dockerfile
- group_service/Dockerfile
- user_service/Dockerfile
> #26 
> CI/CD 관련 설정들
> Dockerfile 작성
> docker-compose.yml 작성
> aws rds-ec2 연결 및 ec2 내부 환경 설정 (rds 일단 퍼블릭으로 열어둬서 나중에 인바운드 규칙 지우고 ec2 내부에서 연동하는 식으로 변경)
> 필요한 secret 환경변수 추가
> github actions workflow 작성
> main 브랜치에서 배포 테스트
>
> CI/CD(#26): 배포 플로우 구축, aws 환경 설정

- .github/workflows/deploy.yml
- content_service/Dockerfile
- content_service/build.gradle
- content_service/src/main/java/api/user/service/UserContentService.java
- content_service/src/main/java/common/config/SwaggerConfig.java
- content_service/src/main/java/io/urdego/content_service/ContentServiceApplication.java
- content_service/src/main/java/io/urdego/content_service/api/user/controller/UserContentController.java
- content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
- content_service/src/main/java/io/urdego/content_service/common/config/SwaggerConfig.java
- content_service/src/main/java/io/urdego/content_service/common/exception/ContentException.java
- content_service/src/main/java/io/urdego/content_service/common/exception/ExceptionMessage.java
- content_service/src/main/java/io/urdego/content_service/common/exception/user/UserContentException.java
- content_service/src/main/java/io/urdego/content_service/domain/entity/BaseEntity.java
- content_service/src/main/java/io/urdego/content_service/domain/entity/user/UserContent.java
- content_service/src/main/java/io/urdego/content_service/domain/entity/user/constant/ContentInfo.java
- content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepository.java
- discovery_service/build.gradle
- docker-compose.yml
- game_service/build.gradle
- gateway_service/Dockerfile
- gateway_service/build.gradle
- gateway_service/src/main/java/config/SwaggerConfig.java
- gateway_service/src/main/java/filter/LoggingFilter.java
- group_service/build.gradle
- group_service/src/main/java/io/urdego/group_service/common/config/SwaggerConfig.java
- user_service/build.gradle
- user_service/src/main/java/io/urdego/user_service/config/SwaggerConfig.java
> #30 
> 전체 마이크로 서비스 배포, swagger 작성
>
> Feature(#30): Main to develop

- discovery_service/Dockerfile
> Refactor(#30) : discovery_service 도커파일 수정

- group_service/.gitignore
- user_service/.gitignore
> Fix: .gitignore 수정

- user_service/build.gradle
- user_service/src/main/java/io/urdego/user_service/api/controller/external/UserController.java
- user_service/src/main/java/io/urdego/user_service/api/controller/external/request/SignInRequest.java
- user_service/src/main/java/io/urdego/user_service/api/controller/external/request/SignUpRequest.java
- user_service/src/main/java/io/urdego/user_service/api/controller/external/request/VerifyNicknameRequest.java
- user_service/src/main/java/io/urdego/user_service/api/controller/external/response/UserInfoResponse.java
- user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
- user_service/src/main/java/io/urdego/user_service/api/controller/internal/response/UserInfo.java
- user_service/src/main/java/io/urdego/user_service/api/controller/request/SignInRequest.java
- user_service/src/main/java/io/urdego/user_service/api/controller/request/VerifyNicknameRequest.java
- user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
- user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
- user_service/src/main/java/io/urdego/user_service/common/constant/HttpStatusConstants.java
- user_service/src/main/java/io/urdego/user_service/common/exception/GlobalExceptionHandler.java
- user_service/src/main/java/io/urdego/user_service/common/exception/UserNotFoundException.java
- user_service/src/main/java/io/urdego/user_service/domain/UserRepository.java
- user_service/src/main/java/io/urdego/user_service/domain/entity/Role.java
- user_service/src/main/java/io/urdego/user_service/domain/entity/User.java
#37 
회원 검색 기능 추가
: 전달 받은 String이 포함된 유저 목록 반환
> Feature: 유저 서비스 - 닉네임으로 회원 목록 조회 추가

- content_service/build.gradle
- content_service/src/main/java/io/urdego/content_service/ContentServiceApplication.java
> Refactor : 배포 테스트

- content_service/src/main/java/io/urdego/content_service/ContentServiceApplication.java
> Bugfix: 충돌해결

- content_service/src/main/java/io/urdego/content_service/api/user/controller/UserContentController.java
- content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
- content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
- content_service/src/main/java/io/urdego/content_service/common/config/ContentServiceConfig.java
- content_service/src/main/java/io/urdego/content_service/common/exception/ExceptionMessage.java
- content_service/src/main/java/io/urdego/content_service/common/exception/user/UserContentException.java
- content_service/src/main/java/io/urdego/content_service/external/aws/service/S3Service.java
#52 
컨텐츠를 삭제한다.
S3 + RDB 일관성 삭제
> Feature(#52): 컨텐츠 단일 삭제

- group_service/src/main/java/io/urdego/group_service/api/controller/group/GroupController.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/CreateGroupReq.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/response/GroupInfoRes.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/response/GroupRes.java
- group_service/src/main/java/io/urdego/group_service/api/controller/groupMember/dto/request/AddGroupMemberReq.java
- group_service/src/main/java/io/urdego/group_service/api/service/group/GroupService.java
- group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/common/client/UserServiceClient.java
- group_service/src/main/java/io/urdego/group_service/domain/entity/group/Group.java
> ex) #이슈번호, #59 
game-service Feign 연결을 위한 group 정보 api refactoring 및 addGroupMember api 수정 
>
> Refactor(#59) : getGroupInfo 추가

- content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentResponse.java
- content_service/src/main/java/io/urdego/content_service/api/user/controller/internal/InternalApiController.java
- content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentService.java
- content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
> Feature(#72): 게임 단일 컨텐츠 정보 조회

- game_service/Dockerfile
> HotFix(#71): game-service Dockerfile 추가

- docker-compose.yml
> HotFix(#71): docker-compose gateway 443 수정

- docker-compose.yml
> HotFix(#71): docker-compose gateway volume 수정

- group_service/build.gradle
- group_service/src/main/java/io/urdego/group_service/api/controller/group/GroupController.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/CreateGroupReq.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/request/UpdateGroupReq.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/dto/response/GroupCreateRes.java
- group_service/src/main/java/io/urdego/group_service/api/service/group/GroupService.java
- group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/common/client/GameServiceClient.java
- group_service/src/main/java/io/urdego/group_service/common/client/NotificationServiceClient.java
- group_service/src/main/java/io/urdego/group_service/common/client/UserServiceClient.java
- group_service/src/main/java/io/urdego/group_service/common/client/request/GroupInfoReq.java
- group_service/src/main/java/io/urdego/group_service/common/client/request/NotificationRequestInfo.java
- group_service/src/main/java/io/urdego/group_service/common/client/request/UserNicknameRequest.java
- group_service/src/main/java/io/urdego/group_service/common/client/response/ResponseUserInfo.java
- group_service/src/main/java/io/urdego/group_service/common/client/response/UserIdListResponse.java
- group_service/src/main/java/io/urdego/group_service/domain/entity/group/Group.java
- user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
- user_service/src/main/java/io/urdego/user_service/api/controller/internal/response/UserIdListResponse.java
- user_service/src/main/java/io/urdego/user_service/api/controller/internal/response/UserNicknameRequest.java
- user_service/src/main/java/io/urdego/user_service/api/service/UserService.java
- user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
close #81 
- 그룹 생성
- 참여 유저들에게 초대 알림 발송
- 게임 생성
- 그룹Id, 게임Id 응답
그룹 생성 _테스트 완료
참여 유저들에게 초대 알림전송 _테스트 완료
게임 생성 _테스트 보류(게임 서비스의 게임 생성 API 미구현)
> Feature : 그룹 생성 API 추가

- group_service/build.gradle
- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/dto/EventType.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/dto/MessageRequest.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/dto/MessageResponse.java
- group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/common/client/request/NotificationRequestInfo.java
- group_service/src/main/java/io/urdego/group_service/common/config/WebSocketConfig.java
> Refactor: 초대 알림 발송 dto 수정

- .idea/jarRepositories.xml
- group_service/build.gradle
- notification_service/src/main/java/com/example/notification_service/NotificationServiceApplication.java
- notification_service/src/main/java/com/example/notification_service/api/controller/NotificationController.java
- notification_service/src/main/java/com/example/notification_service/api/controller/NotificationSseController.java
- notification_service/src/main/java/com/example/notification_service/api/controller/dto/GroupResponseInfo.java
- notification_service/src/main/java/com/example/notification_service/api/controller/dto/NotificationRequestInfo.java
- notification_service/src/main/java/com/example/notification_service/api/controller/dto/UserResponseInfo.java
- notification_service/src/main/java/com/example/notification_service/api/service/NotificationPublisher.java
- notification_service/src/main/java/com/example/notification_service/api/service/SseService.java
- notification_service/src/main/java/com/example/notification_service/api/service/SseServiceImpl.java
- notification_service/src/main/java/com/example/notification_service/common/client/GroupServiceClient.java
- notification_service/src/main/java/com/example/notification_service/common/client/UserServiceClient.java
- notification_service/src/main/java/com/example/notification_service/domain/NotificationMessage.java
- user_service/src/main/java/io/urdego/user_service/UserServiceApplication.java
- user_service/src/main/java/io/urdego/user_service/api/service/UserServiceImpl.java
- user_service/src/main/java/io/urdego/user_service/common/client/NotificationServiceClient.java
> Feature (#51) : Notification-service 중간 결산

- notification_service/src/main/java/com/example/notification_service/api/controller/NotificationSseController.java
- notification_service/src/main/java/com/example/notification_service/api/service/NotificationPublisher.java
- notification_service/src/main/java/com/example/notification_service/api/service/SseService.java
- notification_service/src/main/java/com/example/notification_service/api/service/SseServiceImpl.java
- notification_service/src/main/java/com/example/notification_service/common/client/UserServiceClient.java
- notification_service/src/main/java/com/example/notification_service/config/RedisConfig.java
> Refactor(#51) : SSE email로 변경

- .github/workflows/deploy.yml
- .idea/compiler.xml
- .idea/gradle.xml
- .idea/modules.xml
- .idea/modules/game_service.main.iml
- docker-compose.yml
- notification_service/Dockerfile
> Refactor(#51) : dockerFile 생성

- content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
- gateway_service/.gitignore
> Refactor: 유저 컨텐츠 조회 limit 수정

- gateway_service/src/main/java/io/urdego/gateway_service/config/CorsConfiguration.java
> BugFix: CORS 해결

- discovery_service/src/main/java/io/urdego/discovery_service/config/CorsConfig.java
- game_service/src/main/java/io/urdego/game_service/common/config/CorsConfig.java
- gateway_service/src/main/java/io/urdego/gateway_service/config/CorsConfiguration.java
- notification_service/src/main/java/com/example/notification_service/config/CorsConfig.java
- user_service/src/main/java/io/urdego/user_service/config/CorsConfiguration.java
> Main <- develop

- gateway_service/build.gradle
- gateway_service/src/main/java/io/urdego/gateway_service/config/SwaggerConfig.java
> Swagger: 설정

- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
> Fix(#93) : socket 엔드포인 변수 수정

- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/response/GameStartRes.java
- game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
- game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
> Feature(#93) : game 시작 및 round 종료 관련 로직 수정

- content_service/src/main/java/io/urdego/content_service/common/config/ContentServiceConfig.java
- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/game/dto/response/GameStartRes.java
- game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
- game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
> Feature(#93): game 시작 및 round 종료 관련 로직 수정

- group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/request/CreateGroupReq.java
- group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/domain/entity/group/Group.java
close #119 
- 그룹 생성 API 요청 DTO 수정
- DTO에 따른 상세로직 수정
> Refactor: 그룹 생성 API 수정

- content_service/src/main/java/io/urdego/content_service/common/config/ContentServiceConfig.java
> Main <- devleop

- game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/common/client/dto/response/GroupInfoRes.java
- game_service/src/test/java/io/urdego/game_service/DistanceAndScoreCalculatorTest.java
> HotFix: 게임 쪽 주요 로직 개선, 웹소켓 테스트 완료

- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
close #127 
웹소켓으로 그룹 참여 메시지 발행 시, 실행 로그 확인 코드 추가
> Feature(#127): 그룹 참여 로깅 추가

- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
> Feature(#130): 그룹 참여 로깅 추가 2

- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
- group_service/src/main/java/io/urdego/group_service/api/service/groupMember/GroupMemberServiceImpl.java
> Refactor: log, print문 제거

- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/response/GameStartResponse.java
close #134 
그룹 메시지 전달 - 게임시작 메시지 응답 수정
참여 유저 목록, 라운드 수 추가
> Refactor(#134): 웹 소켓 게임시작 메시지 응답 수정

- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameController.java
- game_service/src/main/java/io/urdego/game_service/api/service/game/GameService.java
- game_service/src/main/java/io/urdego/game_service/api/service/game/GameServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/api/dto/request/GroupCreateReq.java
- group_service/src/main/java/io/urdego/group_service/api/controller/group/websocket/GroupMessageController.java
- group_service/src/main/java/io/urdego/group_service/api/service/group/GroupServiceImpl.java
- group_service/src/main/java/io/urdego/group_service/common/client/GameServiceClient.java
close #92 
그룹 생성시 game-service에 게임 생성 요청
> Feature: 그룹 생성 API - 게임 생성 요청 추가

- .idea/compiler.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/modules/content_service.main.iml
- .idea/modules/user_service.main.iml
- group_service/src/main/resources/logback-spring.xml
- user_service/src/main/resources/logback-spring.xml
> #138 
> logback-spring.xml 파일 설정
> Feature(#138) : add logback files

- group_service/build.gradle
- user_service/build.gradle
> Hotfix(#138): modify gradle

- content_service/src/main/java/io/urdego/content_service/api/user/controller/external/UserContentController.java
- content_service/src/main/java/io/urdego/content_service/common/client/UserServiceClient.java
- user_service/src/main/java/io/urdego/user_service/api/controller/internal/InternalApiController.java
> Refactor: userId -> nickname 변경

- content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentListAndCursorIdxResponse.java
- content_service/src/main/java/io/urdego/content_service/api/user/service/UserContentServiceImpl.java
- content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryCustom.java
- content_service/src/main/java/io/urdego/content_service/domain/entity/user/repository/UserContentRepositoryImpl.java
> Refactor: 유저 전체 컨텐츠수 반환

- content_service/src/main/java/io/urdego/content_service/api/user/controller/external/response/UserContentListAndCursorIdxResponse.java
> Refactor: cursoridx 수정

- .idea/compiler.xml
- .idea/gradle.xml
- .idea/modules.xml
- game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
> Feature: round content limit 3으로 수정

- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
- game_service/src/main/java/io/urdego/game_service/domain/entity/round/Round.java
> Refactor: Socket 구독 destination 전부 동적 경로로 처리

- game_service/build.gradle
- game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/common/config/RedisConfig.java
- game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
> #152 
> redis 분산 락으로 Round 쪽 접근하는 요청들에 대한 동시성 처리
>
> Feature(#152): Round 접근 요청 동시성 처리

- game_service/src/main/java/io/urdego/game_service/api/controller/game/GameSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
- game_service/src/main/java/io/urdego/game_service/domain/entity/round/Round.java
> #152 
> redis 분산 락으로 round 접근 요청 동시성 처리
>
> Feature(#152): 동시성 처리

- game_service/src/main/java/io/urdego/game_service/api/controller/submission/SubmissionSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
> #152 
> round 생성 검증부분 비관적 락 추가
>
> Refactor(#152) : 비관적 락 추가, 예외처리 문구 수정

- game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
> #152 
> 전반적인 로깅 짧게 개선
> 점수 처리 로직 개선
> 중복 제출로 인해 제출 관련 분산 락 수행
>
> Refactor(#152) : 로깅 개선, 점수 처리 로직 개선, 제출 관련 분산 락 수행

- game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
- game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/domain/entity/round/repository/RoundRepository.java
> Refactor(#152) : 점수처리 로직 개선, 라운드 정보 유저 브로드캐스팅 수정

- game_service/src/main/java/io/urdego/game_service/api/controller/round/RoundSocketController.java
> Refactor(#152) : 예외처리 삭제

- game_service/src/main/java/io/urdego/game_service/api/service/round/RoundServiceImpl.java
- game_service/src/main/java/io/urdego/game_service/api/service/submission/SubmissionServiceImpl.java
> Refactor(#152) : 레디스 TTL 수정
